name: Build, Test and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Robot Framework and Selenium
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary selenium webdriver-manager

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-tpop:latest .

    - name: Run container for test
      run: |
        docker run -d -p 8080:80 --name test-container ${{ secrets.DOCKER_USERNAME }}/docker-tpop:latest
        sleep 5
        robot tests/
        docker stop test-container
        docker rm test-container

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-tpop:latest
